### ISSUE TITLE
Out Of Memory at com.automattic.encryptedlogging.model.encryptedlogging.LogEncrypter.encrypt

### ISSUE THREAD

**Issue by khaykov** [Automattic/EncryptedLogging#16]
We got an OOM related to encrypted logging in Day One.

```
Exception java.lang.OutOfMemoryError:
  at java.util.Arrays.copyOf (Arrays.java:3257)
  at java.lang.AbstractStringBuilder.ensureCapacityInternal (AbstractStringBuilder.java:124)
  at java.lang.AbstractStringBuilder.append (AbstractStringBuilder.java:448)
  at java.lang.StringBuilder.append (StringBuilder.java:137)
  at com.automattic.encryptedlogging.model.encryptedlogging.LogEncrypter.encrypt (LogEncrypter.kt:38)
  at com.automattic.encryptedlogging.store.EncryptedLogStore.uploadEncryptedLog (EncryptedLogStore.kt:157)
  at com.automattic.encryptedlogging.store.EncryptedLogStore.uploadNext (EncryptedLogStore.kt:144)
  at com.automattic.encryptedlogging.store.EncryptedLogStore.uploadNextWithDelay (EncryptedLogStore.kt:135)
  at com.automattic.encryptedlogging.store.EncryptedLogStore.access$uploadNextWithDelay (EncryptedLogStore.kt:56)
  at com.automattic.encryptedlogging.store.EncryptedLogStore$uploadNextWithDelay$1.invokeSuspend (EncryptedLogStore.kt:14)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:104)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:584)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:811)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:715)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:702)
```

**Comment by wzieba** [comment]
Another report from the same project: p1754667446732699-slack-C030U03RC8Y

```
E  FATAL EXCEPTION: DefaultDispatcher-worker-7 (Ask Gemini)
    Process: com.dayoneapp.dayone.debug, PID: 24679
    java.lang.OutOfMemoryError: Failed to allocate a 101646488 byte allocation with 25165824 free bytes and 91MB until OOM, target footprint 466430736, growth limit 536870912
    	at java.lang.StringFactory.newStringFromBytes(Native Method)
    	at java.lang.StringLatin1.newString(StringLatin1.java:738)
    	at java.lang.StringBuilder.toString(StringBuilder.java:474)
    	at com.automattic.encryptedlogging.model.encryptedlogging.LogEncrypter.encrypt(LogEncrypter.kt:26)
    	at com.automattic.encryptedlogging.store.EncryptedLogStore.uploadEncryptedLog(EncryptedLogStore.kt:138)
    	at com.automattic.encryptedlogging.store.EncryptedLogStore.uploadNext(EncryptedLogStore.kt:118)
    	at com.automattic.encryptedlogging.store.EncryptedLogStore.access$uploadNext(EncryptedLogStore.kt:33)
    	at com.automattic.encryptedlogging.store.EncryptedLogStore$uploadNext$1.invokeSuspend(Unknown Source:14)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
```

**Comment by ParaskP7** [comment]
FYI: [AINFRA-1217](https://linear.app/a8c/issue/AINFRA-1217)

**Comment by ParaskP7** [comment]
FYI: With #28 merged, this issue should be fixed.
